// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGG7FY7tUb-prWqVbLANUbqHHqQSGB6w4',
    appId: '1:911494921276:web:089484475fda958dee5739',
    messagingSenderId: '911494921276',
    projectId: 'crud-3b96c',
    authDomain: 'crud-3b96c.firebaseapp.com',
    storageBucket: 'crud-3b96c.appspot.com',
    measurementId: 'G-E9DP8H0KB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7BrMFHe3AtuzU_pJyt_9I2ymSjxELTNU',
    appId: '1:911494921276:android:4f16edc8738b4ec5ee5739',
    messagingSenderId: '911494921276',
    projectId: 'crud-3b96c',
    storageBucket: 'crud-3b96c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxZKchZcJA_pVsPCktRS4RM1Z2wuMAEWI',
    appId: '1:911494921276:ios:fc1171e249459512ee5739',
    messagingSenderId: '911494921276',
    projectId: 'crud-3b96c',
    storageBucket: 'crud-3b96c.appspot.com',
    iosClientId: '911494921276-2u0k5sepkl7ko4ae2u0q7smolet59dmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxZKchZcJA_pVsPCktRS4RM1Z2wuMAEWI',
    appId: '1:911494921276:ios:2986e0c5e8016561ee5739',
    messagingSenderId: '911494921276',
    projectId: 'crud-3b96c',
    storageBucket: 'crud-3b96c.appspot.com',
    iosClientId: '911494921276-nta3h176vdcu50j7sgvhvt630rslr785.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrud.RunnerTests',
  );
}
